### ISSUE TITLE
Move docs from RST to MD

### ISSUE THREAD

**Issue by duker33** [fidals/refarm-site#102]
Коротко: переходим с rst на md. Ваши за/против.

------
Наслушался я тут подкастов от ТехРайтеров, как они там rst-доки расхваливают.
Ни с кем не посоветовался, да запустил всю документаху на rst.
А теперь вот думаю, что от этого сплошные неудобства.
Доков у нас немного. А те, что есть, намертво привязаны к разделам.
Получается, мы можем тупо юзать md-файлы, а Гитхаб их сам будет их норм отображать.

Гитхаб не умеет норм отображать rst, если что. И сейчас мы делаем много всего: генерим доки на локали для проверки, генерим их в CI, повесили их на отдельные домены.

В общем, rst было сплошной ошибкой.
Предлагаю перейти на md. Я сам лично перекатаю текущие зачатки доки на md и посношу все следы от rst.

Подкаст: http://devzen.ru/episode-0144/

**Comment by dveselov** [comment]
Вообще, существует readthedocs.org, который умеет собирать rst-документацию из git-репозиториев и публиковать её на своих доменах (`*.readthedocs.io`). Он из коробки понимает sphinx и там, если я правильно помню, вообще нет никаких проблем с настройкой.

С другой стороны, мне больше нравится Markdown, т.к. у него какой-то более человечный синтаксис. Поэтому я не вижу ничего плохого в варианте с размещением доков на гитхабе.

**Comment by duker33** [comment]
@dveselov , да проблем также нету и с локальным сервом. Но всё равно это лишние строки конфигов и кода, настройки и тд.

А маркдаун на Гитхабе - это замечательно, да. Он нам всем уже знаком по работе с комментами и задачами. А ещё можно прямо на гитхабчике отлаживать свою разметку и смотреть на внешний вид. Можно даже создать ветку и закоммитить изменения прямо из интерфейса.
ТехРайтерам (да и всем) это всё будет куда удобнее, чем ставить собирать доку на локали

**Comment by artemiy312** [comment]
Я за md
