### ISSUE TITLE
Expose orders list from admin

### ISSUE THREAD

**Issue by duker33** [fidals/refarm-site#109]
Сейчас заказы отправляются через mail.
Практика показывает, что mail - не самый надёжный механизм.
Часто бывает, бизнесу нужно видеть дампы заказов.

Для этого просто показываем список заказов в Админке в readonly режиме.

Возможно трогать нужно будет только код SE/STB, но не код Рефарма

**Comment by duker33** [comment]
already done on SE: https://github.com/fidals/shopelectro/pull/290

Decide to move it to RF or not

**Comment by artemiy312** [comment]
@duker33 
>Decide to move it to RF or not

SE.Order and STB.Order are different, therefore we  do not have benefits to move logic to RF

**Comment by themygit** [comment]
@duker33 можете в таблицу добавить номер заказа и дату ? сейчас таблица не информативна совсем.
