### ISSUE TITLE
Docker stale images

### ISSUE THREAD

**Issue by artemiy312** [fidals/refarm-site#115]
https://github.com/spotify/docker-gc

We can use that script to collect docker's garbage

------

UPD:
Decided to use it in comments. So, install it on serv and try

**Comment by dveselov** [comment]
Docker have similar built-in command: [docker system prune](https://docs.docker.com/engine/reference/commandline/system_prune/), that works pretty well.

**Comment by artemiy312** [comment]
@dveselov 

I made a comparison for `docker system prune` and `docker-gc`

[My current container list](https://gist.github.com/artemiy312/a01858e6580d6679903c4f58ca7678e5)
- docker system prune
    - [before docker system prune](https://gist.github.com/artemiy312/d635469528742c751282ec1da018297c)
    - [after docker system prune](https://gist.github.com/artemiy312/85fa24ff2940393aecdf67ca4902b06e)
    - [diff before and after prune](https://gist.github.com/artemiy312/fe8131682efebf059fdee8c2f658db8a)
- docker-gc
    - [after docker gc run](https://gist.github.com/artemiy312/a443ac00cd1882a2424160667d11c620)

It seems to me that docker-gc :)

**Comment by artemiy312** [comment]
We have a problem with memory at production machine, so we should integrate it as soon as possible

**Comment by duker33** [comment]
@artemiy312 , i'm working with machine grade already. Smth like this possible `120gb ssd + 500gb hdd`

**Comment by duker33** [comment]
@artemiy312 , launched `docker image prune` on prod serv lately and it worked well.
Images is the main problem, i think.

So, i propose to close this task while we'll not face this problem again

**Comment by duker33** [comment]
@artemiy312 , let's close task?

**Comment by artemiy312** [comment]
@duker33 let's do so
