### ISSUE TITLE
trackers.es6:1: Integrate trackers to STB and SE

### ISSUE THREAD

**Issue by 0pdd** [fidals/refarm-site#129]
The puzzle `292-ba927d60` from #292 has to be resolved:

https://github.com/fidals/refarm-site/blob/b266a28a585db5d12c1465276b8735b8483b6f08/ecommerce/front/trackers.es6#L1-L1

The puzzle was created by Artemiy on 05-Jun-18. 

Estimate: 0 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by artemiy312** [comment]
fidals/shopelectro#292

**Comment by artemiy312** [comment]
@duker33 May I take this issue?

**Comment by duker33** [comment]
@artemiy312 , seems you provided 2much code for `1 hour` in related PR.
This task was hard to split?
I suggest to mark it as `2 hour`.
Remark it if you are agree

**Comment by artemiy312** [comment]
@duker33  PO wants us to complete with this tasks as soon as possible, so I decided to not split it
