### ISSUE TITLE
CI does not work

### ISSUE THREAD

**Issue by artemiy312** [fidals/refarm-site#130]
[CI](https://ci.fidals.com/) does not work again

<img width="639" alt="default" src="https://user-images.githubusercontent.com/13870342/41040313-bd0531be-69a4-11e8-9d61-c0079049fac9.png">

**Comment by artemiy312** [comment]
@duker33 , Please, pay attention

**Comment by artemiy312** [comment]
After the product update, the demon docker died. Trying resurrect him

**Comment by duker33** [comment]
Artemiy resolved it
