### ISSUE TITLE
Use drone workspaces. se2, stb2

### ISSUE THREAD

**Issue by artemiy312** [fidals/refarm-site#132]
Try to use a [workspace:](http://docs.drone.io/workspace/#app-drawer) option for se and stb CI instead of `volumes:`

**Comment by duker33** [comment]
i think we just should remove the most of volumes.
They looks strange now

**Comment by duker33** [comment]
@artemiy312 , i'll just try to rm volume from this discussion:
https://github.com/fidals/stroyprombeton/pull/247#discussion_r202091269

... and from most of other volumes

**Comment by duker33** [comment]
Resolved with https://github.com/fidals/shopelectro/pull/428
