### ISSUE TITLE
Take all tag stuff from SE

### ISSUE THREAD

**Issue by duker33** [fidals/refarm-site#162]
It's required for STB's Tags feature https://github.com/fidals/stroyprombeton/labels/Tags

**Comment by duker33** [comment]
met migrations overhead. I'll work with it at the same task

**Comment by duker33** [comment]
i had to keep all relations and tag stuff's tables on SE (site) side. As we done Product-Catalog with AbstractProduct-AbstractCatalog.

So, no migrations was required

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#164](https://github.com/fidals/refarm-site/issues/164), [#165](https://github.com/fidals/refarm-site/issues/165), [#166](https://github.com/fidals/refarm-site/issues/166) are still not solved.

**Comment by 0pdd** [comment]
@duker33 4 puzzles [#164](https://github.com/fidals/refarm-site/issues/164), [#165](https://github.com/fidals/refarm-site/issues/165), [#166](https://github.com/fidals/refarm-site/issues/166), [#169](https://github.com/fidals/refarm-site/issues/169) are still not solved.

**Comment by 0pdd** [comment]
@duker33 3 puzzles [#164](https://github.com/fidals/refarm-site/issues/164), [#166](https://github.com/fidals/refarm-site/issues/166), [#169](https://github.com/fidals/refarm-site/issues/169) are still not solved; solved: [#165](https://github.com/fidals/refarm-site/issues/165).

**Comment by duker33** [comment]
closed with https://github.com/fidals/shopelectro/pull/541 and https://github.com/fidals/refarm-site/pull/163

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#164](https://github.com/fidals/refarm-site/issues/164), [#166](https://github.com/fidals/refarm-site/issues/166) are still not solved; solved: [#165](https://github.com/fidals/refarm-site/issues/165), [#169](https://github.com/fidals/refarm-site/issues/169).

**Comment by 0pdd** [comment]
@duker33 the puzzle [#166](https://github.com/fidals/refarm-site/issues/166) is still not solved; solved: [#164](https://github.com/fidals/refarm-site/issues/164), [#165](https://github.com/fidals/refarm-site/issues/165), [#169](https://github.com/fidals/refarm-site/issues/169).
