### ISSUE TITLE
test_models.py:246-247: Create fixtures for refarm tests....

### ISSUE THREAD

**Issue by 0pdd** [fidals/refarm-site#165]
The puzzle `162-e3264da6` from #162 has to be resolved:

https://github.com/fidals/refarm-site/blob/512cfa82ec777bb9db66fda2f3ad1580905f0ffa/tests/catalog/test_models.py#L246-L247

The puzzle was created by duker33 on 25-Aug-18. 

Estimate: 60 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by duker33** [comment]
rm https://github.com/fidals/refarm-site/issues/166 pdd task too

**Comment by 0pdd** [comment]
The puzzle `162-e3264da6` has disappeared from the source code, that's why I closed this issue.
