### ISSUE TITLE
Take Tag views to refarm's catalog app

### ISSUE THREAD

**Issue by duker33** [fidals/refarm-site#168]
with tests

it's required for https://github.com/fidals/stroyprombeton/issues/187

**Comment by duker33** [comment]
blocked by https://github.com/fidals/shopelectro/issues/550

We should split code before moving it to refarm side

**Comment by duker33** [comment]
dependency resolved

**Comment by duker33** [comment]
i'll work with `2 hours` task size to decrease review gap.
It's only for hot Tags task

**Comment by duker33** [comment]
faced with few bugs in contexts.
For example PaginationCatalog context don't forward products via pipe.
I'll resolve all this issues in the same task for calendar speed

**Comment by 0pdd** [comment]
@duker33 the puzzle [#179](https://github.com/fidals/refarm-site/issues/179) is still not solved.
