### ISSUE TITLE
models.py:126-127: Rm ProductManager.get_active() method...

### ISSUE THREAD

**Issue by 0pdd** [fidals/refarm-site#169]
The puzzle `164-e0477b7f` from #164 has to be resolved:

https://github.com/fidals/refarm-site/blob/37fee61b1d0d91bb7112a7646725f89488464a46/catalog/models.py#L126-L127

The puzzle was created by duker33 on 27-Aug-18. 

Estimate: 15 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by duker33** [comment]
at SE resolved with https://github.com/fidals/shopelectro/pull/602
