### ISSUE TITLE
context.py:88-89: Move prepare_tile_products func to...

### ISSUE THREAD

**Issue by 0pdd** [fidals/refarm-site#182]
The puzzle `550-f02726e9` from #550 has to be resolved:

https://github.com/fidals/refarm-site/blob/471fe2d1d8b6867da6567126cd1cc6f242764887/catalog/context.py#L88-L89

The puzzle was created by duker33 on 17-Sep-18. 

Estimate: 60 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by duker33** [comment]
method `prepare_...` is broken now. Works only for one site in one refarm's version

**Comment by 0pdd** [comment]
@0pdd the puzzle [#199](https://github.com/fidals/refarm-site/issues/199) is still not solved; solved: [#197](https://github.com/fidals/refarm-site/issues/197), [#198](https://github.com/fidals/refarm-site/issues/198).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#197](https://github.com/fidals/refarm-site/issues/197), [#198](https://github.com/fidals/refarm-site/issues/198), [#199](https://github.com/fidals/refarm-site/issues/199).
