### ISSUE TITLE
context.py:117-121: Move context realization to pure to...

### ISSUE THREAD

**Issue by 0pdd** [fidals/refarm-site#183]
The puzzle `550-c08f412e` from #550 has to be resolved:

https://github.com/fidals/refarm-site/blob/471fe2d1d8b6867da6567126cd1cc6f242764887/catalog/context.py#L117-L121

The puzzle was created by duker33 on 17-Sep-18. 

Estimate: 120 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by duker33** [comment]
search `#183` at all project's code. Many places are needed in this refactor

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#207](https://github.com/fidals/refarm-site/issues/207), [#208](https://github.com/fidals/refarm-site/issues/208) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#208](https://github.com/fidals/refarm-site/issues/208), [#213](https://github.com/fidals/refarm-site/issues/213) are still not solved; solved: [#207](https://github.com/fidals/refarm-site/issues/207).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#213](https://github.com/fidals/refarm-site/issues/213) is still not solved; solved: [#207](https://github.com/fidals/refarm-site/issues/207), [#208](https://github.com/fidals/refarm-site/issues/208).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#239](https://github.com/fidals/refarm-site/issues/239), [#240](https://github.com/fidals/refarm-site/issues/240), [#241](https://github.com/fidals/refarm-site/issues/241) are still not solved; solved: [#207](https://github.com/fidals/refarm-site/issues/207), [#208](https://github.com/fidals/refarm-site/issues/208), [#213](https://github.com/fidals/refarm-site/issues/213).

**Comment by 0pdd** [comment]
@0pdd 6 puzzles [#239](https://github.com/fidals/refarm-site/issues/239), [#240](https://github.com/fidals/refarm-site/issues/240), [#241](https://github.com/fidals/refarm-site/issues/241), [#267](https://github.com/fidals/refarm-site/issues/267), [#268](https://github.com/fidals/refarm-site/issues/268), [#269](https://github.com/fidals/refarm-site/issues/269) are still not solved; solved: [#207](https://github.com/fidals/refarm-site/issues/207), [#208](https://github.com/fidals/refarm-site/issues/208), [#213](https://github.com/fidals/refarm-site/issues/213).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#239](https://github.com/fidals/refarm-site/issues/239), [#267](https://github.com/fidals/refarm-site/issues/267), [#268](https://github.com/fidals/refarm-site/issues/268), [#269](https://github.com/fidals/refarm-site/issues/269) are still not solved; solved: [#207](https://github.com/fidals/refarm-site/issues/207), [#208](https://github.com/fidals/refarm-site/issues/208), [#213](https://github.com/fidals/refarm-site/issues/213), [#240](https://github.com/fidals/refarm-site/issues/240), [#241](https://github.com/fidals/refarm-site/issues/241).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#239](https://github.com/fidals/refarm-site/issues/239), [#268](https://github.com/fidals/refarm-site/issues/268), [#269](https://github.com/fidals/refarm-site/issues/269) are still not solved; solved: [#207](https://github.com/fidals/refarm-site/issues/207), [#208](https://github.com/fidals/refarm-site/issues/208), [#213](https://github.com/fidals/refarm-site/issues/213), [#240](https://github.com/fidals/refarm-site/issues/240), [#241](https://github.com/fidals/refarm-site/issues/241), [#267](https://github.com/fidals/refarm-site/issues/267).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#239](https://github.com/fidals/refarm-site/issues/239), [#269](https://github.com/fidals/refarm-site/issues/269) are still not solved; solved: [#207](https://github.com/fidals/refarm-site/issues/207), [#208](https://github.com/fidals/refarm-site/issues/208), [#213](https://github.com/fidals/refarm-site/issues/213), [#240](https://github.com/fidals/refarm-site/issues/240), [#241](https://github.com/fidals/refarm-site/issues/241), [#267](https://github.com/fidals/refarm-site/issues/267), [#268](https://github.com/fidals/refarm-site/issues/268).
