### ISSUE TITLE
Namespace conflict

### ISSUE THREAD

**Issue by artemiy312** [fidals/refarm-site#211]
Resolve namespace conflict of `catalog.context.py` file and `catalog.context` module

**Comment by duker33** [comment]
@artemiy312 , we can use `import ... as ...` to avoid this conflict.
We already have conflicting name `model` module in many apps, but we don't rename them as newmodel or smth

**Comment by artemiy312** [comment]
@duker33 ,  we had the file and the module named `context` in the module `catalog`, so we had an importing conflict. `from catalog.context import Category` raised an undefined behavior. We will rename `newcontext` to` context` when we have finished refactoring.

**Comment by artemiy312** [comment]
If you still have doubts in the point, you can see [a stack trace of CI build](https://ci.fidals.com/fidals/shopelectro/1012/9) to clarify it

**Comment by duker33** [comment]
@artemiy312 , you meant two versions of context here, sorry.
All's good now
