### ISSUE TITLE
models.py:12-17: Generate image file name with hash. Now...

### ISSUE THREAD

**Issue by 0pdd** [fidals/refarm-site#227]
The puzzle `STB296-d24da08f` from #STB296 has to be resolved: 

https://github.com/fidals/refarm-site/blob/f34dd75d6bcb3348dec6043624b2fcbf706b3267/images/models.py#L12-L17

The puzzle was created by duker33 on 18-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by duker33** [comment]
it's code to gen hash:
```
import hashlib
with open('docker-compose.yml', 'rb') as f:
	res = hashlib.md5(f.read()).hexdigest()
```

Good arch is stayed

**Comment by 0pdd** [comment]
@0pdd the puzzle [#242](https://github.com/fidals/refarm-site/issues/242) is still not solved.
