### ISSUE TITLE
tests_views.py:134: Use fixtures at ecommerce tests

### ISSUE THREAD

**Issue by 0pdd** [fidals/refarm-site#228]
The puzzle `SE619-2b30c42e` from #SE619 has to be resolved: 

https://github.com/fidals/refarm-site/blob/04e279e040811024b8721d8299875df46a00b6fa/tests/ecommerce/tests_views.py#L134-L134

The puzzle was created by duker33 on 20-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by duker33** [comment]
wow, we already have `create_fixtures` command at tests app.
But it's not usable for ecommerce.
Spent this hour on research
