### ISSUE TITLE
test_settings.py:11: Drop `dj_database_url` dependency.

### ISSUE THREAD

**Issue by 0pdd** [fidals/refarm-site#235]
The puzzle `230-5492e443` from #230 has to be resolved: 

https://github.com/fidals/refarm-site/blob/934ee8c4ab4d2909210cfee4976cc83688b1d466/tests/test_settings.py#L11-L11

The puzzle was created by duker33 on 27-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by duker33** [comment]
fixed env file at the same task
