### ISSUE TITLE
__init__.py:3: Annotate methods of Context implementations.

### ISSUE THREAD

**Issue by 0pdd** [fidals/refarm-site#241]
The puzzle `207-ec3d38b3` from #207 has to be resolved: 

https://github.com/fidals/refarm-site/blob/11231f5a529b4ac59cb90239b6bc86e01e5957d2/catalog/newcontext/__init__.py#L3-L3

The puzzle was created by Artemiy on 31-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by duker33** [comment]
@artemiy312 , this task is not clear to me. Context method has all needed functions and docs, as i see.
I close this task. Plz reopen it with description, if you mind
