### ISSUE TITLE
Clarify terms Product, Position and Option

### ISSUE THREAD

**Issue by duker33** [fidals/refarm-site#257]
We created the new Product sub-entity called "Option".
But SE will leave only Product entity.

So, now we have ambiguity between Product, Position and Option terms on refarm side.
Renew namings in code and maybe provide some documentation

**Comment by duker33** [comment]
i'll leave admin packages out of the scope of this task.
We have separated SE tasks block for it

**Comment by 0pdd** [comment]
@duker33 the puzzle [#261](https://github.com/fidals/refarm-site/issues/261) is still not solved.

**Comment by 0pdd** [comment]
@duker33 the puzzle [#318](https://github.com/fidals/refarm-site/issues/318) is still not solved; solved: [#261](https://github.com/fidals/refarm-site/issues/261).

**Comment by 0pdd** [comment]
@duker33 all 2 puzzles are solved here: [#261](https://github.com/fidals/refarm-site/issues/261), [#318](https://github.com/fidals/refarm-site/issues/318).
