### ISSUE TITLE
utils.py:6-8: Create TextView class. Instead of...

### ISSUE THREAD

**Issue by 0pdd** [fidals/refarm-site#268]
The puzzle `240-ac87cf5b` from #240 has to be resolved: 

https://github.com/fidals/refarm-site/blob/f0a73341ce9377759d6b06b9058e8a5fc6cd4574/pages/utils.py#L6-L8

The puzzle was created by duker33 on 14-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by duker33** [comment]
it's about arch

**Comment by duker33** [comment]
this task is not actual, i just drop it

**Comment by 0pdd** [comment]
The puzzle `240-ac87cf5b` has disappeared from the source code, that's why I closed this issue.
