### ISSUE TITLE
Fix pdd bot

### ISSUE THREAD

**Issue by artemiy312** [fidals/refarm-site#279]
ERROR: ecommerce/views.py; puzzle at line #26; TODO found, but puzzle can't be parsed, most probably because TODO is not followed by a puzzle marker, as this page explains: https://github.com/yegor256/pdd#how-to-format
If you can't understand the cause of this issue or you don't know how to fix it, please submit a GitHub issue, we will try to help you: https://github.com/yegor256/pdd/issues. This tool is still in its beta version and we will appreciate your feedback. Here is where you can find more documentation: https://github.com/yegor256/pdd/blob/master/README.md.
Exit code is 1

**Comment by 0pdd** [comment]
@artemiy312 the puzzle [#281](https://github.com/fidals/refarm-site/issues/281) is still not solved.
