### ISSUE TITLE
models.py:230: Apply new order_by_alphanumeric for SE/STB.

### ISSUE THREAD

**Issue by 0pdd** [fidals/refarm-site#282]
The puzzle `273-db0487f5` from #273 has to be resolved: 

https://github.com/fidals/refarm-site/blob/1ca2bc841b8715ecdf2ee765b83722086ab79b81/catalog/models.py#L230-L230

The puzzle was created by Artemiy on 21-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by artemiy312** [comment]
Wait for fidals/stroyprombeton#452

**Comment by 0pdd** [comment]
@0pdd the puzzle [#294](https://github.com/fidals/refarm-site/issues/294) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#294](https://github.com/fidals/refarm-site/issues/294) is solved here.
