### ISSUE TITLE
models.py:232: Create an index for order_by_alphanumeric...

### ISSUE THREAD

**Issue by 0pdd** [fidals/refarm-site#283]
The puzzle `273-b2ae754f` from #273 has to be resolved: 

https://github.com/fidals/refarm-site/blob/1ca2bc841b8715ecdf2ee765b83722086ab79b81/catalog/models.py#L232-L232

The puzzle was created by Artemiy on 21-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by artemiy312** [comment]
Django doesn't provide suitable ability to create indexes. So i have to do it myself. I don't want to split this issue on sub-tasks, so i will increase the estimate

**Comment by 0pdd** [comment]
@0pdd the puzzle [#292](https://github.com/fidals/refarm-site/issues/292) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#292](https://github.com/fidals/refarm-site/issues/292) is still not solved; solved: [#129](https://github.com/fidals/refarm-site/issues/129).
