### ISSUE TITLE
models.py:256-258: Rm `get_group_tags_pairs`. Use...

### ISSUE THREAD

**Issue by 0pdd** [fidals/refarm-site#291]
The puzzle `SE747-53839270` from #SE747 has to be resolved: 

https://github.com/fidals/refarm-site/blob/355abaedf6b0d28c688f40d873e7a9e44e8e906e/catalog/models.py#L256-L258

The puzzle was created by @duker33 on 22-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by artemiy312** [comment]
I'd prefer to remove `groupby`, that requires ordered input

**Comment by 0pdd** [comment]
The puzzle `SE747-53839270` has disappeared from the source code, that's why I closed this issue.
