### ISSUE TITLE
models.py:145: Use the new catalog arch at sites.

### ISSUE THREAD

**Issue by 0pdd** [fidals/refarm-site#318]
The puzzle `261-a4b1299c` from #261 has to be resolved: 

https://github.com/fidals/refarm-site/blob/c6d422044ad35073a2824b73fcd678d3739d5efe/catalog/models.py#L145-L145

The puzzle was created by duker33 on 04-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by duker33** [comment]
duplicates https://github.com/fidals/shopelectro/issues/805
