### ISSUE TITLE
Refactor and test breadcrumbs mech

### ISSUE THREAD

**Issue by duker33** [fidals/refarm-site#343]
Inspired by https://github.com/fidals/shopelectro/issues/961

This code `pages.templatetags.pages_extras.breadcrumbs_with_siblings` is monolithic and not tested.
Make it flexible and cover with unit tests

**Comment by 0pdd** [comment]
@duker33 the puzzle [#345](https://github.com/fidals/refarm-site/issues/345) is still not solved; solved: [#136](https://github.com/fidals/refarm-site/issues/136).

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#347](https://github.com/fidals/refarm-site/issues/347), [#348](https://github.com/fidals/refarm-site/issues/348) are still not solved; solved: [#136](https://github.com/fidals/refarm-site/issues/136), [#345](https://github.com/fidals/refarm-site/issues/345).
