### ISSUE TITLE
Refactor Search Arch

### ISSUE THREAD

**Issue by duker33** [fidals/refarm-site#85]
В рамках задачи FullText Search, переделываем архитектуру Search.

Олег уже оставил PRs на эту тему. Проверь, подчисти их и выставляй на Ревью

Автор: Дюк

Выносим search в отдельный app

Автор: Дима

**Comment by duker33** [comment]
PRs от Олега:
https://github.com/fidals/refarm-site/pull/74
https://github.com/fidals/shopelectro/pull/155/files
https://github.com/fidals/stroyprombeton/pull/101

**Comment by duker33** [comment]
выставил PR по самой объёмной части - refarm-site

**Comment by duker33** [comment]
нес-ко часов страдал на SE с селениум-тестами.
Похоже, бага была в самом селениуме.
Странно, что она не возникает в CI

**Comment by duker33** [comment]
SE замержили и даже запродили.
Остался STB, там конь не валялся. Но сделаю по аналогии с SE быстро

**Comment by duker33** [comment]
в Бетоне сделал https://github.com/fidals/stroyprombeton/pull/139

**Comment by 0pdd** [comment]
@duker33 2 puzzles [#117](https://github.com/fidals/refarm-site/issues/117), [#119](https://github.com/fidals/refarm-site/issues/119) are still not solved; solved: [#118](https://github.com/fidals/refarm-site/issues/118).
