### ISSUE TITLE
Remove config.py

### ISSUE THREAD

**Issue by duker33** [fidals/refarm-site#89]
Выпилим config.py с сайтов. Переносим его содержимое в settings, utils и т.д.

MAIN_PAGE_TILE делаем отдельной сущностью в базе и прикручиваем к админке

**Comment by duker33** [comment]
@Filarius обнаружил, что задача неактуальна.

Я имел ввиду выпилить config.py с обоих сайтов. Сейчас посмотрел и обнаружил, что на STB его уже выпилили, осталась только SE.
Сдублирую задачу туда, а эту закрою.

**Comment by Filarius** [comment]
Судя по всему в рамках данного репозитория ни config.py ни одна из его дочерних сущностей не используется.
И похоже что и скрипты, напрямую использующие функции и переменные из config.py в данном репозитории тоже не используются.
