### ISSUE TITLE
Research Selenium Grid

### ISSUE THREAD

**Issue by duker33** [fidals/refarm-site#91]
Разобраться с Selenium Grid (понять нужен ли он вообще)

Автор: Дима

**Comment by duker33** [comment]
знаю, что долго разбирались с Селениумом. Не знаю, трогали ли при этом selenium grid

**Comment by dveselov** [comment]
Grid нужен для очень комплексных тестов - он объединяет разные версии разных браузеров, запущенные на разных операционных системах и позволяет использовать их через обобщенный интерфейс. Мне кажется, нам это пока что не нужно.
