### ISSUE TITLE
Апгрейд сервера

### ISSUE THREAD

**Issue by dveselov** [fidals/refarm-site#96]
Нужно решить, как поступить с сервером: обновить существующую конфигурацию или перенести CI на отдельный сервер.

**Comment by duker33** [comment]
подождём начала активной разработки. Тогда станет ясно - страдаем ли от совмещённого с сервом CI и будем решать

**Comment by duker33** [comment]
created gCalendar personal mention for 05.07

**Comment by duker33** [comment]
we'll leave CI on current serv
